version: '3'
services:
  db:
    image: redis:latest
    container_name: db
    networks:
      - apollonet
  apolloserver:
   image: "radkin/apolloserver:latest"
   build: .
   ports:
     - '9000'
  lb:
    image: dockercloud/haproxy
    ports:
      - '80:80'
    links:
      - apolloserver
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  apollonet:
    driver: bridge
